spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    password: zhmf74no
    username: sergshubin

    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

queue:
  name: mail





